"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createRack, createSubZone, createWarehouse, createZone, getRacks, getSession, getSubZones, getWarehouses, getZones, logout, type RackRecord, type Session, type SubZoneRecord, type WarehouseRecord, type ZoneRecord } from "../lib/api";
import { WorkspaceShell } from "./workspace-shell";

type Kind = "warehouse" | "zone" | "sub-zone" | "rack";
const labels: Record<Kind, { title: string; plural: string; parent?: string }> = { warehouse: { title: "Warehouse", plural: "warehouses" }, zone: { title: "Zone", plural: "zones", parent: "Warehouse" }, "sub-zone": { title: "Sub Zone", plural: "sub-zones", parent: "Zone" }, rack: { title: "Rack", plural: "racks", parent: "Sub Zone" } };

export function HierarchyListPage({ kind }: { kind: Kind }) {
  const router = useRouter(); const [session, setSession] = useState<Session | null>(null); const [rows, setRows] = useState<Array<WarehouseRecord | ZoneRecord | SubZoneRecord | RackRecord>>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const label = labels[kind];
  useEffect(() => { let mounted = true; getSession().then((current) => { if (!mounted) return; setSession(current); const loaders = { warehouse: getWarehouses, zone: getZones, "sub-zone": getSubZones, rack: getRacks }; return loaders[kind]().then((response) => { if (mounted) setRows(response.data); }); }).catch((e) => { if (!mounted) return; if (statusOf(e) === 401) router.replace("/"); else setError(e instanceof Error ? e.message : `Unable to load ${label.plural}.`); }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [kind, label.plural, router]);
  async function handleLogout() { try { await logout(); } finally { router.replace("/"); } }
  if (loading || !session) return <main className="session-loading"><span className="brand-mark">G</span><p>Loading {label.plural}...</p></main>;
  return <WorkspaceShell activeItem={label.title} user={session.user} onLogout={handleLogout}><div className="page-intro permission-intro"><div><p className="eyebrow">WAREHOUSE ATTRIBUTES</p><h1>{label.title}</h1><p className="intro-copy">Manage {label.plural} and their hierarchy.</p></div><button className="primary-button compact-button" onClick={() => router.push(`/${kind}/new`)}>Create new <span aria-hidden="true">+</span></button></div>{error ? <section className="data-error panel"><h2>{label.title} data unavailable</h2><p>{error}</p><button className="outline-button" onClick={() => window.location.reload()}>Try again</button></section> : <HierarchyTable kind={kind} rows={rows} />}</WorkspaceShell>;
}

function HierarchyTable({ kind, rows }: { kind: Kind; rows: Array<WarehouseRecord | ZoneRecord | SubZoneRecord | RackRecord> }) {
  return <section className="permission-table-wrap panel"><div className="table-summary"><div><strong>{rows.length}</strong><span>{labels[kind].plural}</span></div><span className="data-badge">{rows.filter((row) => row.status === "ACTIVE").length} active</span></div><div className="permission-table-scroll"><table className="permission-table hierarchy-table"><thead><tr><th>Id</th><th>Name</th><th>Code</th>{kind !== "warehouse" && <th>Parent</th>}<th>Status</th><th>Created</th></tr></thead><tbody>{rows.length === 0 ? <tr><td className="table-empty" colSpan={kind === "warehouse" ? 5 : 6}>No records found.</td></tr> : rows.map((row) => <tr key={row.id}><td className="id-cell">{row.id}</td><td><strong>{row.name}</strong><span className="module-key">{row.description || "No description"}</span></td><td className="code-cell">{row.code}</td>{kind !== "warehouse" && <td>{parentName(row, kind)}</td>}<td><span className={`role-status ${row.status.toLowerCase()}`}>{row.status}</span></td><td className="date-cell">{formatDate(row.createdAt)}</td></tr>)}</tbody></table></div></section>;
}

function parentName(row: WarehouseRecord | ZoneRecord | SubZoneRecord | RackRecord, kind: Kind) { if (kind === "zone") { const item = row as ZoneRecord; return `${item.warehouse.name} (${item.warehouse.code})`; } if (kind === "sub-zone") { const item = row as SubZoneRecord; return `${item.zone.name} (${item.zone.code})`; } const item = row as RackRecord; return `${item.subZone.name} (${item.subZone.code})`; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
function statusOf(error: unknown) { return error instanceof Error && "status" in error ? (error as { status?: number }).status : undefined; }

export function HierarchyCreatePage({ kind }: { kind: Kind }) {
  const router = useRouter(); const label = labels[kind]; const [session, setSession] = useState<Session | null>(null); const [parents, setParents] = useState<Array<WarehouseRecord | ZoneRecord | SubZoneRecord>>([]); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [description, setDescription] = useState(""); const [parentId, setParentId] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { let mounted = true; getSession().then((current) => { if (!mounted) return; setSession(current); if (kind === "warehouse") return; const loaders = { zone: getWarehouses, "sub-zone": getZones, rack: getSubZones }; return loaders[kind]().then((response) => { if (mounted) setParents(response.data); }); }).catch((e) => { if (mounted) { if (statusOf(e) === 401) router.replace("/"); else setError(e instanceof Error ? e.message : `Unable to load ${label.parent?.toLowerCase()}s.`); } }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [kind, label.parent, router]);
  async function handleLogout() { try { await logout(); } finally { router.replace("/"); } }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (name.trim().length < 2 || code.trim().length < 1 || (kind !== "warehouse" && !parentId)) { setError(`Name, code, and ${label.parent?.toLowerCase()} are required.`); return; } setError(""); setSaving(true); try { const payload = { name: name.trim(), code: code.trim(), description: description.trim() || undefined }; if (kind === "warehouse") await createWarehouse(payload); if (kind === "zone") await createZone({ ...payload, warehouseId: Number(parentId) }); if (kind === "sub-zone") await createSubZone({ ...payload, zoneId: Number(parentId) }); if (kind === "rack") await createRack({ ...payload, subZoneId: Number(parentId) }); router.push(`/${kind}`); } catch (e) { setError(e instanceof Error ? e.message : `Unable to create ${label.title.toLowerCase()}.`); } finally { setSaving(false); } }
  if (loading || !session) return <main className="session-loading"><span className="brand-mark">G</span><p>Loading {label.title.toLowerCase()} form...</p></main>;
  return <WorkspaceShell activeItem={label.title} breadcrumb={`${label.title} / New`} user={session.user} onLogout={handleLogout}><div className="page-intro permission-intro"><div><p className="eyebrow">WAREHOUSE ATTRIBUTES</p><h1>New {label.title.toLowerCase()}</h1><p className="intro-copy">Add a {label.title.toLowerCase()} to the warehouse hierarchy.</p></div></div><form className="permission-form hierarchy-form" onSubmit={submit}><section className="panel form-section"><div className="form-section-heading"><div><p className="eyebrow">{label.title.toUpperCase()} DETAILS</p><h2>Identity</h2></div><span className="required-note">* Required</span></div><label htmlFor="hierarchy-name">Name</label><input id="hierarchy-name" value={name} onChange={(e) => setName(e.target.value)} placeholder={`e.g. Main ${label.title}`} maxLength={100} required /><label htmlFor="hierarchy-code">Code</label><input id="hierarchy-code" value={code} onChange={(e) => setCode(e.target.value)} placeholder="e.g. MAIN-01" maxLength={50} required /><label htmlFor="hierarchy-description">Description</label><textarea id="hierarchy-description" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Optional description" maxLength={500} />{kind !== "warehouse" && <><label htmlFor="hierarchy-parent">{label.parent}</label><select id="hierarchy-parent" value={parentId} onChange={(e) => setParentId(e.target.value)} required><option value="">Select {label.parent?.toLowerCase()}</option>{parents.map((parent) => <option value={parent.id} key={parent.id}>{parent.name} ({parent.code})</option>)}</select>{parents.length === 0 && <p className="field-hint">No parent records are available. Create an active {label.parent?.toLowerCase()} first.</p>}</>}</section>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="outline-button" onClick={() => router.push(`/${kind}`)}>Cancel</button><button type="submit" className="primary-button compact-button" disabled={saving || (kind !== "warehouse" && parents.length === 0)}>{saving ? "Creating..." : `Create ${label.title.toLowerCase()}`}<span aria-hidden="true">-&gt;</span></button></div></form></WorkspaceShell>;
}